general.import = [
    # uncomment the theme you want
    # "~/.config/alacritty/themes/catppuccin-mocha.toml"
    # "~/.config/alacritty/themes/dracula.toml"
    # "~/.config/alacritty/themes/gruvbox-dark.toml"
    "~/.config/alacritty/themes/gruvbox-dark-medium.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Medium"

[window]
decorations = "None"
blur = true
opacity = 0.9

