theme="gruvbox"

[editor]
true-color=true 
line-number = "relative"

[keys.normal]
"C-c" = "no_op"
g = {c = { c = "toggle_comments"}}

[keys.insert]
"C-c" = "normal_mode"

[keys.select]
g = {c = { c = "toggle_comments"}}
"C-c" = "normal_mode"
